export { default as CourseRouter } from "./course.route";
export { default as DiaryRouter } from "./diary.route";
export { default as UserRouter } from "./user.route";
export { default as WordRouter } from "./word.route";
export { default as AuthRouter } from "./auth.route";
export { default as PublicRouter } from "./public.route";
export { default as LessionRouter } from "./lession.route";
export { default as RoundRouter } from "./round.route";
export { default as TestBankRouter } from "./testBank.route";
