export * as UserController from "./user.controller";
export * as AuthController from "./auth.controller";
export * as CourseController from "./course.controller";
export * as PublicController from "./public.controller";
export * as WordController from "./word.controller";
export * as LessionController from "./lession.controller";
export * as RoundController from "./round.controller";
export * as DiaryController from "./diary.controller";
export * as TestBankController from "./testBank.controller";
